const projects=window.__unfinishedProjects;
projects.forEach((p,i)=>document.querySelector('#heroArt'+i).innerHTML=art(p));
const tabs=document.getElementById('tabs'),showcase=document.getElementById('showcase');let active=0;
function render(){
 const p=projects[active];
 tabs.innerHTML=projects.map((x,i)=>`<button class="${i===active?'active':''}" data-tab="${i}" style="--project-accent:${x.accent}"><span>${x.number}</span><strong>${x.title}</strong><small>${x.completion}% ready</small></button>`).join('');
 showcase.style.cssText=`--project-accent:${p.accent};--project-soft:${p.soft};--project-surface:${p.surface}`;
 const r=52,c=2*Math.PI*r,o=c-(p.completion/100)*c;
 showcase.innerHTML=`<article class="showcase-main glass-panel"><div class="showcase-meta"><span>${p.label}</span><span>${p.stage}</span></div><div class="showcase-art">${art(p)}</div><div class="showcase-copy"><div><p class="mono-label">Opportunity ${p.number}</p><h3>${p.title}</h3></div><p>${p.summary}</p></div></article><article class="metric-card glass-panel metric-readiness"><div class="metric-label">✦ Acquisition readiness</div><div class="readiness-ring"><svg viewBox="0 0 128 128"><circle cx="64" cy="64" r="${r}" class="ring-track"/><circle cx="64" cy="64" r="${r}" class="ring-value" style="stroke:${p.accent};stroke-dasharray:${c};stroke-dashoffset:${o}"/></svg><div><strong>${p.completion}</strong><span>%</span></div></div><p>Weighted across product, build, deployment, documentation, security, commercial readiness, and transferability.</p></article><article class="metric-card glass-panel metric-price"><div class="metric-label">$ Acquisition</div><div class="price-stack"><span>Private guide</span><strong>${p.guidePrice}</strong><small>Accelerated close · ${p.buyNow}</small></div><button class="inline-link" data-inquiry="Start buy-now process">Start the process →</button></article><article class="metric-card glass-panel metric-assets"><div class="metric-label">▤ Built depth</div><strong class="asset-number">${p.proofValue}</strong><p><b>${p.proofLabel}</b><br>${p.proofDetail}</p></article><article class="buyer-card glass-panel"><div><p class="mono-label">Best next owner</p><h4>${p.buyer}</h4></div><p>${p.opportunity}</p><div class="buyer-actions"><button class="ui-button ui-button--default ui-button--md" data-detail>View the full brief →</button><button class="ui-button ui-button--secondary ui-button--md" data-inquiry="Make a private offer">Make an offer</button></div></article>`;
 bind();
}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{active=+b.dataset.tab;render()});document.querySelectorAll('[data-inquiry]').forEach(b=>b.onclick=()=>openInquiry(b.dataset.inquiry));document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=openDetail)}
function openDetail(){const p=projects[active];document.getElementById('detailContent').innerHTML=`<div class="project-dialog-hero" style="--project-accent:${p.accent};--project-soft:${p.soft};--project-surface:${p.surface}"><div class="project-dialog-art">${art(p)}</div><div class="project-dialog-title"><span>Opportunity ${p.number} · ${p.stage}</span><h2 class="dialog-title">${p.title}</h2></div></div><div class="project-dialog-body"><p class="dialog-description">${p.summary}</p><div class="dialog-metric-row"><div><span>Acquisition readiness</span><strong>${p.completion}%</strong></div><div><span>Private guide</span><strong>${p.guidePrice}</strong></div><div><span>Fast-track close</span><strong>${p.buyNow}</strong></div><div><span>Sale format</span><strong>${p.priceMode}</strong></div></div><div class="dialog-detail-grid"><section><p class="mono-label">Included in the acquisition</p><ul>${p.includes.map(x=>`<li>✓ ${x}</li>`).join('')}</ul></section><section><p class="mono-label">What the next owner finishes</p><ul>${p.remains.map(x=>`<li>→ ${x}</li>`).join('')}</ul></section></div><section class="diligence-panel"><div><p class="mono-label">Known diligence boundaries</p><span>The details a serious buyer should understand before interpreting the readiness score.</span></div><ul>${p.diligence.map(x=>`<li>✓ ${x}</li>`).join('')}</ul></section><section class="founder-note"><p class="mono-label">The honest founder note</p><blockquote>“${p.reason}”</blockquote></section><div class="dialog-actions"><button class="ui-button ui-button--default ui-button--lg" data-inquiry="Request private room">Request the private room →</button><button class="ui-button ui-button--secondary ui-button--lg" data-inquiry="Start buy-now process">Start buy-now process</button></div></div>`;document.getElementById('detailModal').classList.add('open');bind()}
function openInquiry(intent){document.getElementById('detailModal').classList.remove('open');document.getElementById('inquiryTitle').textContent=intent;document.getElementById('inquiryDescription').textContent=intent==='Join buyer list'?'Get the next three opportunities before the public release.':`Raise your hand for ${projects[active].title}. Enough context now saves both sides time later.`;document.getElementById('inquiryModal').classList.add('open')}
document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>document.querySelectorAll('.preview-modal').forEach(m=>m.classList.remove('open')));const menu=document.getElementById('menu'),mobileNav=document.getElementById('mobileNav');function setMobileNav(open){mobileNav.style.display=open?'block':'none';menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'×':'☰'}menu.onclick=()=>setMobileNav(menu.getAttribute('aria-expanded')!=='true');mobileNav.querySelectorAll('a').forEach(a=>a.onclick=()=>setMobileNav(false));
const faqData=[['Am I buying a company or a collection of files?','Each listing says exactly what is for sale. Some are asset purchases—code, brand, domain, plans, and related IP. Others may include an operating entity, revenue, contracts, or customers when those items are legally transferable.'],['Why are offers private instead of a live auction?','A small, curated catalog does not need public bidding theater. Sealed offers preserve urgency without allowing one weak opening bid to publicly anchor the asset.'],['What happens after I click buy now?','It starts an accelerated qualification and closing process. It is not a one-click credit-card transfer. Both sides confirm fit and terms, sign the definitive agreement, fund escrow, and complete the documented asset transfer.'],['Do customer records or lead lists automatically transfer?','No. Every data asset is reviewed separately for ownership, contract restrictions, privacy commitments, consent, and applicable law.'],['Will Brennan remain involved after the sale?','Each listing states the exact transition package. The default structure includes documentation, recorded walkthroughs, credential transfer, two live transition calls, and a defined post-close question window.']];document.getElementById('faqs').innerHTML=faqData.map((x,i)=>`<div class="accordion-item ${i===0?'open':''}"><h3 class="accordion-header"><button class="accordion-trigger"><span>${x[0]}</span><span class="accordion-plus">+</span></button></h3><div class="accordion-content"><div class="accordion-content-inner">${x[1]}</div></div></div>`).join('');document.querySelectorAll('.accordion-trigger').forEach(b=>b.onclick=()=>b.closest('.accordion-item').classList.toggle('open'));
document.getElementById('inquiryForm').onsubmit=e=>{e.preventDefault();e.target.innerHTML='<div class="form-success form-wide"><div>✓</div><h3>You’re on the list.</h3><p>Preview mode is working. Connect LEAD_WEBHOOK_URL before public launch.</p></div>'};
function updateCountdown(){const remaining=new Date('2026-09-05T20:00:00-05:00').getTime()-Date.now(),el=document.getElementById('countdown');if(!el)return;if(remaining<=0){el.textContent='Offers closed';return}const d=Math.floor(remaining/86400000),h=Math.floor(remaining%86400000/3600000),m=Math.floor(remaining%3600000/60000),s=Math.floor(remaining%60000/1000);el.textContent=`${String(d).padStart(2,'0')}d  ${String(h).padStart(2,'0')}h  ${String(m).padStart(2,'0')}m  ${String(s).padStart(2,'0')}s`;}
updateCountdown();setInterval(updateCountdown,1000);render();bind();
